version: '3.1'
services:
 webapp:
  image: gkdevops/dockerrepository:11
  restart: always
  container_name: mvnwebapp
  ports:
  - 8080:8080
  networks:
  - mvnappnetwork
networks:
 mvnappnetwork:
  driver: bridge

